export const ALL_MLB_STADIUMS = [
  // American League East
  { id: "yankee-stadium", name: "Yankee Stadium", team: "New York Yankees", lat: 40.8296, lng: -73.9262, league: "AL" },
  { id: "fenway-park", name: "Fenway Park", team: "Boston Red Sox", lat: 42.3467, lng: -71.0972, league: "AL" },
  { id: "camden-yards", name: "Oriole Park at Camden Yards", team: "Baltimore Orioles", lat: 39.2838, lng: -76.6216, league: "AL" },
  { id: "tropicana-field", name: "Tropicana Field", team: "Tampa Bay Rays", lat: 27.7682, lng: -82.6534, league: "AL" },
  { id: "rogers-centre", name: "Rogers Centre", team: "Toronto Blue Jays", lat: 43.6414, lng: -79.3894, league: "AL" },
  // American League Central
  { id: "guaranteed-rate", name: "Guaranteed Rate Field", team: "Chicago White Sox", lat: 41.8299, lng: -87.6338, league: "AL" },
  { id: "progressive-field", name: "Progressive Field", team: "Cleveland Guardians", lat: 41.4962, lng: -81.6852, league: "AL" },
  { id: "comerica-park", name: "Comerica Park", team: "Detroit Tigers", lat: 42.3390, lng: -83.0485, league: "AL" },
  { id: "kauffman-stadium", name: "Kauffman Stadium", team: "Kansas City Royals", lat: 39.0517, lng: -94.4803, league: "AL" },
  { id: "target-field", name: "Target Field", team: "Minnesota Twins", lat: 44.9817, lng: -93.2776, league: "AL" },
  // American League West
  { id: "minute-maid", name: "Minute Maid Park", team: "Houston Astros", lat: 29.7573, lng: -95.3555, league: "AL" },
  { id: "angel-stadium", name: "Angel Stadium", team: "Los Angeles Angels", lat: 33.8003, lng: -117.8827, league: "AL" },
  { id: "oakland-coliseum", name: "Oakland Coliseum", team: "Oakland Athletics", lat: 37.7516, lng: -122.2005, league: "AL" },
  { id: "t-mobile-park", name: "T-Mobile Park", team: "Seattle Mariners", lat: 47.5914, lng: -122.3325, league: "AL" },
  { id: "globe-life", name: "Globe Life Field", team: "Texas Rangers", lat: 32.7512, lng: -97.0832, league: "AL" },
  // National League East
  { id: "truist-park", name: "Truist Park", team: "Atlanta Braves", lat: 33.8911, lng: -84.4681, league: "NL" },
  { id: "loandepot-park", name: "loanDepot park", team: "Miami Marlins", lat: 25.7781, lng: -80.2196, league: "NL" },
  { id: "citi-field", name: "Citi Field", team: "New York Mets", lat: 40.7571, lng: -73.8458, league: "NL" },
  { id: "citizens-bank", name: "Citizens Bank Park", team: "Philadelphia Phillies", lat: 39.9061, lng: -75.1665, league: "NL" },
  { id: "nationals-park", name: "Nationals Park", team: "Washington Nationals", lat: 38.8730, lng: -77.0074, league: "NL" },
  // National League Central
  { id: "wrigley-field", name: "Wrigley Field", team: "Chicago Cubs", lat: 41.9484, lng: -87.6553, league: "NL" },
  { id: "great-american", name: "Great American Ball Park", team: "Cincinnati Reds", lat: 39.0975, lng: -84.5070, league: "NL" },
  { id: "american-family", name: "American Family Field", team: "Milwaukee Brewers", lat: 43.0280, lng: -87.9712, league: "NL" },
  { id: "pnc-park", name: "PNC Park", team: "Pittsburgh Pirates", lat: 40.4469, lng: -80.0058, league: "NL" },
  { id: "busch-stadium", name: "Busch Stadium", team: "St. Louis Cardinals", lat: 38.6226, lng: -90.1928, league: "NL" },
  // National League West
  { id: "chase-field", name: "Chase Field", team: "Arizona Diamondbacks", lat: 33.4455, lng: -112.0667, league: "NL" },
  { id: "coors-field", name: "Coors Field", team: "Colorado Rockies", lat: 39.7559, lng: -104.9942, league: "NL" },
  { id: "dodger-stadium", name: "Dodger Stadium", team: "Los Angeles Dodgers", lat: 34.0739, lng: -118.2400, league: "NL" },
  { id: "petco-park", name: "Petco Park", team: "San Diego Padres", lat: 32.7076, lng: -117.1570, league: "NL" },
  { id: "oracle-park", name: "Oracle Park", team: "San Francisco Giants", lat: 37.7786, lng: -122.3893, league: "NL" },
];

export const VISITS = [
  {
    stadiumId: "oakland-coliseum",
    date: "2017-05-20",
    awayTeam: "Boston Red Sox", awayScore: 3,
    homeTeam: "Oakland Athletics", homeScore: 8,
    boxscoreUrl: "https://www.mlb.com/gameday/490734/final",
    photo: "/photos/oakland-coliseum.jpg",
    wp: "Sean Manaea", lp: "Drew Pomeranz", sv: null,
    attendance: 20235, weather: "Sunny", temp: 79, wind: "8 mph, Out To RF",
    duration: 202,
    year: 2017,
  },
  {
    stadiumId: "yankee-stadium",
    date: "2017-06-08",
    awayTeam: "Boston Red Sox", awayScore: 1,
    homeTeam: "New York Yankees", homeScore: 9,
    boxscoreUrl: "https://www.mlb.com/gameday/490994/final",
    photo: "/photos/yankee-stadium.jpg",
    wp: "Masahiro Tanaka", lp: "David Price", sv: "Dellin Betances",
    attendance: 46194, weather: "Cloudy", temp: 62, wind: "9 mph, In From RF",
    duration: 207,
    year: 2017,
  },
  {
    stadiumId: "oracle-park",
    date: "2017-07-07",
    awayTeam: "Miami Marlins", awayScore: 6,
    homeTeam: "San Francisco Giants", homeScore: 1,
    boxscoreUrl: "https://www.mlb.com/gameday/491398/final",
    photo: "/photos/oracle-park.jpg",
    wp: "Dan Straily", lp: "Matt Moore", sv: "Kyle Barraclough",
    attendance: 41510, weather: "Clear", temp: 72, wind: "17 mph, Out To CF",
    duration: 160,
    year: 2017,
  },
  {
    stadiumId: "guaranteed-rate",
    date: "2017-09-02",
    awayTeam: "Tampa Bay Rays", awayScore: 4,
    homeTeam: "Chicago White Sox", homeScore: 5,
    boxscoreUrl: "https://www.mlb.com/gameday/492130/final",
    photo: "/photos/guaranteed-rate.jpg",
    wp: "Carlos Rodon", lp: "Chris Archer", sv: null,
    attendance: 17700, weather: "Partly Cloudy", temp: 72, wind: "7 mph, In From LF",
    duration: 194,
    year: 2017,
  },
  {
    stadiumId: "wrigley-field",
    date: "2017-09-03",
    awayTeam: "Atlanta Braves", awayScore: 5,
    homeTeam: "Chicago Cubs", homeScore: 1,
    boxscoreUrl: "https://www.mlb.com/gameday/492134/final",
    photo: "/photos/wrigley-field.jpg",
    wp: "Max Fried", lp: "Mike Montgomery", sv: null,
    attendance: 42145, weather: "Sunny", temp: 81, wind: "11 mph, Varies",
    duration: 163,
    year: 2017,
  },
  {
    stadiumId: "target-field",
    date: "2017-09-29",
    awayTeam: "Detroit Tigers", awayScore: 3,
    homeTeam: "Minnesota Twins", homeScore: 6,
    boxscoreUrl: "https://www.mlb.com/gameday/492489/final",
    photo: "/photos/target-field.jpg",
    wp: "Kyle Gibson", lp: "Matthew Boyd", sv: null,
    attendance: 34580, weather: "Partly Cloudy", temp: 59, wind: "5 mph, In From LF",
    duration: 209,
    year: 2017,
  },
  {
    stadiumId: "fenway-park",
    date: "2018-05-28",
    awayTeam: "Toronto Blue Jays", awayScore: 3,
    homeTeam: "Boston Red Sox", homeScore: 8,
    boxscoreUrl: "https://www.mlb.com/gameday/530212/final",
    photo: "/photos/fenway-park.jpg",
    wp: "Rick Porcello", lp: "Aaron Sanchez", sv: null,
    attendance: 34700, weather: "Cloudy", temp: 53, wind: "7 mph, In From CF",
    duration: 174,
    year: 2018,
  },
  {
    stadiumId: "american-family",
    date: "2019-03-31",
    awayTeam: "St. Louis Cardinals", awayScore: 4,
    homeTeam: "Milwaukee Brewers", homeScore: 5,
    boxscoreUrl: "https://www.mlb.com/gameday/567555/final",
    photo: "/photos/american-family.jpg",
    wp: "Corbin Burnes", lp: "Michael Wacha", sv: null,
    attendance: 35042, weather: "Roof Closed", temp: 60, wind: null,
    duration: 174,
    year: 2019,
  },
  {
    stadiumId: "busch-stadium",
    date: "2019-04-28",
    awayTeam: "Cincinnati Reds", awayScore: 2,
    homeTeam: "St. Louis Cardinals", homeScore: 5,
    boxscoreUrl: "https://www.mlb.com/gameday/566582/final",
    photo: "/photos/busch-stadium.jpg",
    wp: "Jack Flaherty", lp: "Sonny Gray", sv: null,
    attendance: 45701, weather: "Sunny", temp: 51, wind: "9 mph, In From RF",
    duration: 173,
    year: 2019,
  },
  {
    stadiumId: "kauffman-stadium",
    date: "2019-05-01",
    awayTeam: "Tampa Bay Rays", awayScore: 2,
    homeTeam: "Kansas City Royals", homeScore: 3,
    boxscoreUrl: "https://www.mlb.com/gameday/565719/final",
    photo: "/photos/kauffman-stadium.jpg",
    wp: "Jakob Junis", lp: "Ryne Stanek", sv: null,
    attendance: 15087, weather: "Overcast", temp: 60, wind: "2 mph, L To R",
    duration: 157,
    year: 2019,
  },
  {
    stadiumId: "t-mobile-park",
    date: "2019-05-18",
    awayTeam: "Minnesota Twins", awayScore: 18,
    homeTeam: "Seattle Mariners", homeScore: 4,
    boxscoreUrl: "https://www.mlb.com/gameday/566394/final",
    photo: "/photos/t-mobile-park.jpg",
    wp: "Wade LeBlanc", lp: "Jose Berrios", sv: null,
    attendance: 34440, weather: "Partly Cloudy", temp: 68, wind: "3 mph, In From LF",
    duration: 230,
    year: 2019,
  },
  {
    stadiumId: "loandepot-park",
    date: "2022-09-13",
    awayTeam: "Philadelphia Phillies", awayScore: 2,
    homeTeam: "Miami Marlins", homeScore: 1,
    boxscoreUrl: "https://www.mlb.com/gameday/661320/final",
    photo: "/photos/loandepot-park.jpg",
    wp: "Bailey Falter", lp: "Sandy Alcantara", sv: "David Robertson",
    attendance: 5801, weather: "Roof Closed", temp: 72, wind: null,
    duration: 154,
    year: 2022,
  },
  {
    stadiumId: "nationals-park",
    date: "2024-08-31",
    awayTeam: "Chicago Cubs", awayScore: 5,
    homeTeam: "Washington Nationals", homeScore: 3,
    boxscoreUrl: "https://www.mlb.com/gameday/744808/final",
    photo: "/photos/nationals-park.jpg",
    wp: "Javier Assad", lp: "DJ Herz", sv: "Porter Hodge",
    attendance: 32995, weather: "Cloudy", temp: 83, wind: "5 mph, Out To CF",
    duration: 158,
    year: 2024,
  },
  {
    stadiumId: "citizens-bank",
    date: "2024-09-01",
    awayTeam: "Atlanta Braves", awayScore: 2,
    homeTeam: "Philadelphia Phillies", homeScore: 3,
    extra: "F/11",
    boxscoreUrl: "https://www.mlb.com/gameday/745536/final",
    photo: "/photos/citizens-bank.jpg",
    wp: "Spencer Schwellenbach", lp: "Aaron Bummer", sv: "Raisel Iglesias",
    attendance: 43249, weather: "Partly Cloudy", temp: 83, wind: "10 mph, Out To RF",
    duration: 194,
    year: 2024,
  },
  {
    stadiumId: "camden-yards",
    date: "2024-09-02",
    awayTeam: "Chicago White Sox", awayScore: 3,
    homeTeam: "Baltimore Orioles", homeScore: 13,
    boxscoreUrl: "https://www.mlb.com/gameday/746992/final",
    photo: "/photos/camden-yards.jpg",
    wp: "Corbin Burnes", lp: "Chris Flexen", sv: null,
    attendance: 35906, weather: "Sunny", temp: 81, wind: "8 mph, In From LF",
    duration: 194,
    year: 2024,
  },
];

export const EXTRA_GAMES = [
  {
    stadiumId: "t-mobile-park",
    date: "2015-06-01",
    gamePk: 414416,
    awayTeam: "New York Yankees", awayScore: 7,
    homeTeam: "Seattle Mariners", homeScore: 2,
  },
  {
    stadiumId: "t-mobile-park",
    date: "2015-07-12",
    gamePk: 414973,
    awayTeam: "Los Angeles Angels", awayScore: 10,
    homeTeam: "Seattle Mariners", homeScore: 3,
  },
  {
    stadiumId: "t-mobile-park",
    date: "2016-07-18",
    gamePk: 448250,
    awayTeam: "Chicago White Sox", awayScore: 3,
    homeTeam: "Seattle Mariners", homeScore: 4,
  },
  {
    stadiumId: "target-field",
    date: "2018-06-22",
    gamePk: 530541,
    awayTeam: "Texas Rangers", awayScore: 8,
    homeTeam: "Minnesota Twins", homeScore: 1,
  },
  {
    stadiumId: "t-mobile-park",
    date: "2022-04-16",
    gamePk: 662206,
    awayTeam: "Houston Astros", awayScore: 4,
    homeTeam: "Seattle Mariners", homeScore: 0,
  },
  {
    stadiumId: "t-mobile-park",
    date: "2023-07-10",
    gamePk: null,
    event: "hr-derby",
    label: "Home Run Derby",
    description: "T-Mobile Home Run Derby — Won by Vladimir Guerrero Jr.",
  },
  {
    stadiumId: "t-mobile-park",
    date: "2023-07-11",
    gamePk: 717421,
    event: "all-star",
    label: "All-Star Game",
    awayTeam: "National League", awayScore: 3,
    homeTeam: "American League", homeScore: 2,
  },
  {
    stadiumId: "t-mobile-park",
    date: "2024-09-29",
    gamePk: 745201,
    awayTeam: "Oakland Athletics", awayScore: 4,
    homeTeam: "Seattle Mariners", homeScore: 6,
  },
  {
    stadiumId: "t-mobile-park",
    date: "2025-10-17",
    gamePk: 813039,
    event: "playoff",
    label: "ALCS Game 5",
    awayTeam: "Toronto Blue Jays", awayScore: 2,
    homeTeam: "Seattle Mariners", homeScore: 6,
  },
  {
    stadiumId: "t-mobile-park",
    date: "2026-04-10",
    gamePk: 823156,
    awayTeam: "Houston Astros", awayScore: 6,
    homeTeam: "Seattle Mariners", homeScore: 9,
  },
];

export const TEAM_COLORS = {
  "New York Yankees": { primary: "#003087", secondary: "#E4002C" },
  "Boston Red Sox": { primary: "#BD3039", secondary: "#0C2340" },
  "Baltimore Orioles": { primary: "#DF4601", secondary: "#27251F" },
  "Tampa Bay Rays": { primary: "#092C5C", secondary: "#8FBCE6" },
  "Toronto Blue Jays": { primary: "#134A8E", secondary: "#1D2D5C" },
  "Chicago White Sox": { primary: "#27251F", secondary: "#C4CED4" },
  "Cleveland Guardians": { primary: "#00385D", secondary: "#E31937" },
  "Detroit Tigers": { primary: "#0C2340", secondary: "#FA4616" },
  "Kansas City Royals": { primary: "#004687", secondary: "#BD9B60" },
  "Minnesota Twins": { primary: "#002B5C", secondary: "#D31145" },
  "Houston Astros": { primary: "#002D62", secondary: "#EB6E1F" },
  "Los Angeles Angels": { primary: "#BA0021", secondary: "#003263" },
  "Oakland Athletics": { primary: "#003831", secondary: "#EFB21E" },
  "Seattle Mariners": { primary: "#0C2C56", secondary: "#005C5C" },
  "Texas Rangers": { primary: "#003278", secondary: "#C0111F" },
  "Atlanta Braves": { primary: "#CE1141", secondary: "#13274F" },
  "Miami Marlins": { primary: "#00A3E0", secondary: "#EF3340" },
  "New York Mets": { primary: "#002D72", secondary: "#FF5910" },
  "Philadelphia Phillies": { primary: "#E81828", secondary: "#002D72" },
  "Washington Nationals": { primary: "#AB0003", secondary: "#14225A" },
  "Chicago Cubs": { primary: "#0E3386", secondary: "#CC3433" },
  "Cincinnati Reds": { primary: "#C6011F", secondary: "#000000" },
  "Milwaukee Brewers": { primary: "#FFC52F", secondary: "#12284B" },
  "Pittsburgh Pirates": { primary: "#27251F", secondary: "#FDB827" },
  "St. Louis Cardinals": { primary: "#C41E3A", secondary: "#0C2340" },
  "Arizona Diamondbacks": { primary: "#A71930", secondary: "#E3D4AD" },
  "Colorado Rockies": { primary: "#333366", secondary: "#131413" },
  "Los Angeles Dodgers": { primary: "#005A9C", secondary: "#A5ACAF" },
  "San Diego Padres": { primary: "#2F241D", secondary: "#FFC425" },
  "San Francisco Giants": { primary: "#FD5A1E", secondary: "#27251F" },
};

export const TEAM_IDS = {
  "Arizona Diamondbacks": 109,
  "Atlanta Braves": 144,
  "Baltimore Orioles": 110,
  "Boston Red Sox": 111,
  "Chicago Cubs": 112,
  "Chicago White Sox": 145,
  "Cincinnati Reds": 113,
  "Cleveland Guardians": 114,
  "Colorado Rockies": 115,
  "Detroit Tigers": 116,
  "Houston Astros": 117,
  "Kansas City Royals": 118,
  "Los Angeles Angels": 108,
  "Los Angeles Dodgers": 119,
  "Miami Marlins": 146,
  "Milwaukee Brewers": 158,
  "Minnesota Twins": 142,
  "New York Mets": 121,
  "New York Yankees": 147,
  "Oakland Athletics": 133,
  "Philadelphia Phillies": 143,
  "Pittsburgh Pirates": 134,
  "San Diego Padres": 135,
  "San Francisco Giants": 137,
  "Seattle Mariners": 136,
  "St. Louis Cardinals": 138,
  "Tampa Bay Rays": 139,
  "Texas Rangers": 140,
  "Toronto Blue Jays": 141,
  "Washington Nationals": 120,
  "American League": 159,
  "National League": 160,
};
